
redis-options:
  addr: 127.0.0.1:6379
  username:
  password:
  db: 0

auth-mode: 1  # 0 Anonymous, 1 Username, 2 ClientID
auth-prefix: comqtt-auth
acl-mode: 2  # 0 Anonymous, 1 Username, 2 ClientID
acl-prefix: comqtt-acl