apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8mqtt2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8mqtt2
  template:
    metadata:
      labels:
        app: k8mqtt2
    spec:
      containers:
        - name: k8mqtt2
          image: gcr.io/iserveustaging/comqtt@sha256:cef8333fc054a36467fcbc8a5d78b6d323c58c38459233564e9f6f61e717b45b
          ports:
          - containerPort: 80
          - containerPort: 7946
          - containerPort: 8946
          - containerPort: 17946
          - containerPort: 1883
          - containerPort: 1882
          - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: IP
              value: "34.47.181.2:7946"
            - name: RaftBootstrap
              value: "false"
            - name: advertise-addr
              value: "34.47.170.202"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: k8mqtt2
spec:
  selector:
    app: k8mqtt2
  ports:
    - protocol: TCP
      name: rest
      port: 80
      targetPort: 80
    - protocol: TCP
      name: gossip
      port: 7946
      targetPort: 7946
    - protocol: TCP
      name: raft
      port: 8946
      targetPort: 8946
    - protocol: TCP
      name: grpc
      port: 17946
      targetPort: 17946
    - protocol: TCP
      name: tcp
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: ws
      port: 1882
      targetPort: 1882
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
