apiVersion: apps/v1
kind: Deployment
metadata:
  name: comqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comqtt
  template:
    metadata:
      labels:
        app: comqtt
    spec:
      containers:
        - name: comqtt
          image: gcr.io/iserveustaging/comqtt@sha256:2cf7de6db2c4b78e3fcebeb39924987013dc01fdd57eb67e5b6effe486c4eb47
          command: [ "/bin/sh", "-c", "env" ]
          ports:
          - containerPort: 80
          - containerPort: 7946
          - containerPort: 8946
          - containerPort: 17946
          - containerPort: 1883
          - containerPort: 1882
          - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: comqtt
spec:
  selector:
    app: comqtt
  ports:
    - protocol: TCP
      name: rest
      port: 80
      targetPort: 80
    - protocol: TCP
      name: gossip
      port: 7946
      targetPort: 7946
    - protocol: TCP
      name: raft
      port: 8946
      targetPort: 8946
    - protocol: TCP
      name: grpc
      port: 17946
      targetPort: 17946
    - protocol: TCP
      name: tcp
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: ws
      port: 1882
      targetPort: 1882
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
