apiVersion: apps/v1
kind: Deployment
metadata:
  name: comqtt2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comqtt2
  template:
    metadata:
      labels:
        app: comqtt2
    spec:
      containers:
        - name: comqtt2
          image: gcr.io/iserveustaging/comqtt@sha256:ecace167c90b2d176a9103a673581038df6f2543dfa2e2484830a21b3b16d80e
          # command: [ "/bin/sh", "-c", "env" ]
          ports:
          - containerPort: 80
          - containerPort: 7946
          - containerPort: 8946
          - containerPort: 17946
          - containerPort: 1883
          - containerPort: 1882
          - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: IP
              value: ""
            - name: RaftBootstrap
              value: true
            - name: NODE-NAME
              value: 
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: comqtt2
spec:
  selector:
    app: comqtt2
  ports:
    - protocol: TCP
      name: rest
      port: 80
      targetPort: 80
    - protocol: TCP
      name: gossip
      port: 7946
      targetPort: 7946
    - protocol: TCP
      name: raft
      port: 8946
      targetPort: 8946
    - protocol: TCP
      name: grpc
      port: 17946
      targetPort: 17946
    - protocol: TCP
      name: tcp
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: ws
      port: 1882
      targetPort: 1882
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
